# * pybullet_planning
# blocklist
# branches:
#   except:
#   - master
#   - caelan

# safelist
# branches:
#   only:
#   - dev
#   - master

language: python

python:
#   - "2.7"
  - "3.6"

before_install:
# - pip install Cython --install-option="--no-cython-compile"
- pip install cmake
install:
- pip install --no-cache-dir -r requirements-dev.txt

script:
- pip install ikfast_pybind
- invoke test
after_success:
  - coveralls
